#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'
require 'yaml'
require 'optparse'

require 'jekyll-indico/cache'

options = { config: '_config.yml' }

OptionParser.new do |opts|
  opts.on('-c', '--config=FILE', 'Read a config file') do |c|
    options[:config] = c
  end
end.parse!

puts "Reading #{options[:config]}"

config = YAML.safe_load(File.read(options[:config]))
indico = JekyllIndico.config_from(config['indico'])

JekyllIndico.cache(indico[:url], indico[:ids], indico[:data]) do |name, number|
  puts "Accessing #{number} for #{name}"
end
